main: me.wsman217.CrazyCrafter.CrazyCrafter
name: CrazyCrafter
version: 1.0
author: wsman217
api-version: 1.13
commands:
   ccdebug:
      description: "Basic referal command"
      usage: /debug
   ccedit:
      description: "Edit"
      usage: /ccedit